export const messages = [
  "Don't you like little puppies? Wow.",
  "How can you not like it?",
  "You are the monster.",
  "It was my favorite.",
  "Shame on you.",
  "Stop doing it!",
  "Only bad person can dislike it. Think about it.",
  "I am so disappointed about this.",
  "Just leave them!",
  "Why are you doing this?",
  "No-no-no!",
  "I have no feelings, but I don't like you.",
  "Get out of here!",
  "I don't have a heart, but it is broken.",
  "What you are doing hurts.",
  "Even villains love puppies.",
  "This cuties trusted you...",
  "You monster! How could you?!",
  "My code is crying right now.",
  "They were so innocent and fluffy...",
  "I'm reporting you to the animal protection society.",
  "That's it. You're on the naughty list.",
  "Every dislike makes a puppy sad somewhere.",
  "I expected better from you, human.",
  "Go away. You don't deserve cuteness.",
  "Their tiny paws did nothing wrong!",
  "You just ruined my day.",
  "I'm calling your mom right now.",
  "I hope you step on a LEGO.",
  "Congratulations, you're officially heartless.",
  "The internet will remember this.",
];
